### PR TITLE
add CDNJS

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Hi there,

CDNJS now also hosts umbrellajs, hope this info can also be shown to users, thanks!

### CODE REVIEW

**Comment by franciscop** [comment]
Hi, are there any advantage of CDNJS over jsdelivr? I'm ready to change the main one if so, however adding two buttons for the same function doesn't really make sense because of [Decision fatigue](https://en.m.wikipedia.org/wiki/Decision_fatigue)+bloating.

**Comment by PeterDaveHello** [comment]
CDNJS totally supports both http/2.0 spdy and directly hosted on cloudflare :smile:

**Comment by franciscop** [comment]
Okay, just asked about it in jsdelivr. However they also support major, minor and patch versions, which is really versatile when making demos/support (I almost always use major or minor):

- https://cdn.jsdelivr.net/umbrella/2/umbrella.min.js
- https://cdn.jsdelivr.net/umbrella/2.0/umbrella.min.js
- https://cdn.jsdelivr.net/umbrella/2.0.4/umbrella.min.js

So I won't be updating it.

PS: a disclaimer saying that [you work for CDNJS](https://cdnjs.com/about) would have been really nice. Otherwise it feels like you are just trying to marketing/sell your CDN.

**Comment by PeterDaveHello** [comment]
> PS: a disclaimer saying that you work for CDNJS would have been really nice. Otherwise it feels like you are just trying to marketing/sell your CDN.

Not a work for me, we are not a company or something, just try to let libraries' authors know that they can use CDNJS, but it's up to you :)

**Pull request closed without merging**
